### PR TITLE
Add pagination to retrieve_txs API call

### PR DESCRIPTION
**Pull request by invis87**

### CODE REVIEW

**Comment by yeastplume** [comment]
Hi, thanks for the PR. Could you please provide a description of what the PR addresses and what it hopes to accomplish?

I'm not sure the notion of 'Pagination' is something that needs to be considered in the API. Why can't clients take care of it at the display level?

**Comment by yeastplume** [comment]
There's also a suggestion for a more fully-featured filter mechanism here, which you might consider adding to or weighing in on somehow: https://github.com/mimblewimble/grin-wallet/pull/127

**Comment by DavidBurkett** [comment]
@yeastplume Pagination is usually done on the server side for performance reasons. The retrieve_txs call is kind of slow, so it makes sense to do this here.

**Comment by invis87** [comment]
@yeastplume Hi. This PR is for pagination on retrieve_tx API, issue for it: https://github.com/mimblewimble/grin/issues/2776
Pagination should be done on both sides to save traffic and improve speed.

**Comment by yeastplume** [comment]
I can take that point. Have had more of a think, and I do think this functionality should be thought of in the context of a more generic query filter rather than bolting on two specific arguments to the API, such as in #2776 (where it's all done client side, so perhaps an amalgamation of approaches is needed). We can discuss this between now and post 2.0.0

**Comment by yeastplume** [comment]
Closing due to lack of activity, feel free to bring up again in wallet subteam.

**Pull request closed without merging**
