### PR TITLE
[DNM] [5.0.x] Replace custom hyper client with reqwest

### PR DESCRIPTION
**Pull request by jaspervdm**
Right now our HTTP client that interfaces with the node and other wallets is using some pretty low level hyper code. It uses separate dependencies for tls and timeouts. On top of that, it uses a Tokio runtime that is spun up for every request separately, which is inefficient and tends to fail at some point (see https://github.com/mimblewimble/grin-wallet/issues/509).

This PR replaces the hyper code by the [reqwest](https://github.com/seanmonstar/reqwest) library, which is well reviewed and maintained and using it simplifies our code.

Instead of creating a tokio runtime for each request, use a global runtime. Unfortunately, until reqwest updates to tokio 0.3, the runtime will have to be behind a `Mutex`.

### CODE REVIEW

**Comment by quentinlesceller** [comment]
This seems a great improvement 👍 .
> Could use some help with testing the tor socks proxy, if anyone feels like it.

Sure ping me anytime!

**Comment by jaspervdm** [comment]
For some reason the tests are failing on Windows, I will try to debug it on my machine after the weekend as I don't have access to it before then.

**Comment by quentinlesceller** [comment]
Looks like a random error. I triggered another run.

**Comment by b-wg** [comment]
This seems good, any other issues with this PR? Can we merge it now?

**Comment by phyro** [comment]
@quentinlesceller can we close this one?

**Comment by quentinlesceller** [comment]
Yes indeed we can close this one.

**Pull request closed without merging**
