### PR TITLE
Remove method from grin-wallet.yml and keybase.rs from adapters

### PR DESCRIPTION
**Pull request by s7500**
This PR solves part of the [issue](https://github.com/mimblewimble/grin-wallet/issues/580)
Doesn't break consensus
No additional unit tests needed
All tests passed

### CODE REVIEW

**Comment by phyro** [comment]
Thanks for the contribution @s7500 . I'll take a look into it a bit more later when I get to my PC. One thing that comes to mind is that removing keybase adapter would also require removing `keybase_notify_ttl` config option.

**Comment by s7500** [comment]
Thanks @phyro, that's a good note!
I also removed it in the new commit

**Comment by s7500** [comment]
Sorry, my mistake
I should trust my ide less

**Comment by yeastplume** [comment]
Looks good, thanks for this. I remember it being annoying having to maintain that unused keybase adapter, so happy to have it removed from the code.

**Review by yeastplume — APPROVED** [review]

**Pull request merged**
