### PR TITLE
Replace custom hyper client with reqwest

### PR DESCRIPTION
**Pull request by quentinlesceller**
Taken from https://github.com/mimblewimble/grin-wallet/pull/520. All credits to @jaspervdm.

### CODE REVIEW

**Comment by quentinlesceller** [comment]
How to build and test:

```bash
git clone https://github.com/quentinlesceller/grin-wallet.git
cd grin-wallet
git checkout node_client_master
cargo build --release
```

Now try basic stuff such as API, sending transactions etc...

**Comment by GeneFerneau** [comment]
tACK - ran the full test suite + `tor_dev_helper::socks_tor` test, all successful :rocket:

**Comment by phyro** [comment]
are some of these covered by https://github.com/mimblewimble/grin-wallet/blob/master/tests/owner_v3_lifecycle.rs#L47 ?

**Comment by phyro** [comment]
@pkariz could you build this branch and check a few of the wallet API endpoint + making some transaction? 🙏

**Comment by quentinlesceller** [comment]
I'm getting:
```
20210330 11:51:54.969 WARN grin_wallet_controller::controller - Slatepack Address is: tgrin16g8vng2q8er82yh35h4rc9xsqr94mkrhl23t2w9g97znhzg7dt6qmd8lwc
^[b20210330 11:52:44.616 ERROR grin_util::logger -
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.': /Users/quentin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:38   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: grin_util::logger::send_panic_to_log::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: tokio::runtime::enter::enter
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::context::enter
  10: grin_wallet_impls::client_utils::client::Client::send_request
  11: grin_wallet_impls::client_utils::client::Client::post
  12: <grin_wallet_impls::node_clients::http::HTTPNodeClient as grin_wallet_libwallet::types::NodeClient>::get_version_info
  13: <grin_wallet_api::foreign::Foreign<L,C,K> as grin_wallet_api::foreign_rpc::ForeignRpc>::check_version
  14: <dyn grin_wallet_api::foreign_rpc::ForeignRpc as easy_jsonrpc_mw::Handler>::handle
  15: easy_jsonrpc_mw::handle_call
  16: easy_jsonrpc_mw::handle_parsed_request
  17: easy_jsonrpc_mw::Handler::handle_request
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
  20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
  21: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  22: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  24: tokio::runtime::task::raw::poll
  25: std::thread::local::LocalKey<T>::with
  26: tokio::runtime::thread_pool::worker::Context::run_task
  27: tokio::runtime::thread_pool::worker::Context::run
  28: tokio::macros::scoped_tls::ScopedKey<T>::set
  29: tokio::runtime::thread_pool::worker::run
  30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: tokio::runtime::task::harness::Harness<T,S>::poll
  33: tokio::runtime::blocking::pool::Inner::run
  34: tokio::runtime::context::enter
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
  37: std::sys::unix::thread::Thread::new::thread_start
  38: __pthread_start



Thread 'tokio-runtime-worker' panicked with message:
"Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks."
See /Users/quentin/.grin/test/grin-wallet.log for further details.
``` 
When trying to receive Grin.

**Comment by phyro** [comment]
I think this may be similar to the fix here, but am not sure https://github.com/mimblewimble/grin-wallet/pull/552. I do remember seeing a couple of issues e.g. [this one](https://github.com/mimblewimble/grin-wallet/issues/559) where if you click on the linked gist you see the same error message.

**Comment by quentinlesceller** [comment]
Indeed good catch @phyro ! Will fix in a bit

**Comment by quentinlesceller** [comment]
Ok I can confirm that it works with the fix in #552.

**Comment by quentinlesceller** [comment]
Need more testing now.

**Comment by phyro** [comment]
@quentinlesceller I'm now wondering how come this change is not present in master branch. I can never remember the release flow we use but I think we may have forgotten to merge the release into master on grin-wallet. If this is the case, I'd remove this commit, sync master with the release branch and then rebase this PR.

**Comment by phyro** [comment]
Sorry, I think I know what confused me and I believe it was a false alarm on my end. The fix you added in the 2nd commit is already present on master which is why there is no diff with it on this PR and I didn't check this. We can forget my comment above

**Comment by phyro** [comment]
@pkariz could you test the endpoints you used for the exchange on this updated version when you find the time? 🙏 (if you find the time also some random ones)

**Comment by antiochp** [comment]
Looks like we have a conflict in `cargo.lock` from another merged PR.

**Comment by quentinlesceller** [comment]
Fixed.

**Comment by antiochp** [comment]
Tested various operations and interactions and looks good. :+1:
The fix from #552 was my main concern and all seems solid.

**Review by antiochp — APPROVED** [review]
:+1:

**Comment by phyro** [comment]
are we good to merge this one?

**Pull request merged**
