### PR TITLE
Fix Tor send

### LINKED ISSUE #418: Cannot send with Tor on latest master
Thanks to @mably, we found this issue on latest master:

```
grin-wallet --floonet send -d volyuczoexpctup3dzqfybnh4tz4xsh6zow6r3wcd4y7yugb67r3iuyd -f  1
```
fails with
```
Wallet command failed: Generic error: Invalid wallet comm type and destination. method: http, dest: volyuczoexpctup3dzqfybnh4tz4xsh6zow6r3wcd4y7yugb67r3iuyd
```

this same command works on grin v3.1.1.

### PR DESCRIPTION
**Pull request by quentinlesceller**
Fixes #418.

### CODE REVIEW

**Comment by yeastplume** [comment]
Can you change the `hyper-socks2` include in the `impls` crate to:

```
hyper-socks2 = { git = "https://github.com/yeastplume/hyper-socks2", branch = "master" }
```

And ensure TOR sends are working

**Comment by quentinlesceller** [comment]
Yes!

**Comment by quentinlesceller** [comment]
Just sent with Tor with success. However, this part of the code
https://github.com/mimblewimble/grin-wallet/pull/422/files#diff-b73b7157d2d3dab84ee755bcac8c4e4cL325-L328
```
let other_version = v_sender.check_other_version(&url_str)?;
 				if other_version == SlateVersion::V3 {
 					args.target_slate_version = Some(3);
 				}
```
Needs Tor so either I find a clever way to avoid this check or I have to spawn the Tor process at this point.
If I spawn the Tor Process at this point maybe I can pass a running_bool to send_tx to avoid starting Tor again.

But considering this code will only be triggered between 4.0.0 release and HF3 it might be okay to spawn two times the Tor process.

**Comment by yeastplume** [comment]
> Just sent with Tor with success. However, this part of the code
> https://github.com/mimblewimble/grin-wallet/pull/422/files#diff-b73b7157d2d3dab84ee755bcac8c4e4cL325-L328
> 
> ```
> let other_version = v_sender.check_other_version(&url_str)?;
>  				if other_version == SlateVersion::V3 {
>  					args.target_slate_version = Some(3);
>  				}
> ```
> 
> Needs Tor so either I find a clever way to avoid this check or I have to spawn the Tor process at this point.
> If I spawn the Tor Process at this point maybe I can pass a running_bool to send_tx to avoid starting Tor again.
> 
> But considering this code will only be triggered between 4.0.0 release and HF3 it might be okay to spawn two times the Tor process.

Yes, this is a bit broken here, but I'm rewriting this so it works in #423. I might be able to refactor there to avoid spawning the tor process twice, but if it turns too messy then it's no big deal, there will only be a short period where this code will be triggered.

**Comment by quentinlesceller** [comment]
@yeastplume ready for review. The Tor process is spawned twice. Tested and was able to send.

**Comment by yeastplume** [comment]
Did you mean to target this at the 3.1.x branch? (This is completely superseded on master by slatepack workflow changes in #423)

**Comment by quentinlesceller** [comment]
In that case I can close that one and keep #424 for 3.1.x branch.

**Pull request closed without merging**
