### PR TITLE
remove height argument from fee related functions as per fixpastfees RFC

### PR DESCRIPTION
**Pull request by tromp**
name: fixpastfees
about: remove dependence of fee() and fee_shift() functions on height
title: 'fix past fees'

Companion PR for

https://github.com/mimblewimble/grin/pull/3629

both implementing RFC https://github.com/mimblewimble/grin-rfcs/blob/master/text/0021-fix-prior-fees.md
to extend the 40 bit fee restriction and use of fee shifts back beyond HF4 to all history.
Technically a Hard Fork, but if we have a many month reorg introducing a > 40 bit fee prior to HF4, we have bigger problems to deal with than a chain split.

This simplifies all fee related functions as they no longer need a height argument to distinguish preHF4 from postHF4 behaviour.

### CODE REVIEW

**Comment by phyro** [comment]
@tromp this one seems to have some failing tests

**Comment by tromp** [comment]
how to add revieers again?

**Comment by GeneFerneau** [comment]
Had to run a `cargo update` to bump the `master` version locally, maybe the CI needs it too?

**Comment by GeneFerneau** [comment]
`git add Cargo.lock`?

**Review by GeneFerneau — APPROVED** [review]

**Review by DavidBurkett — APPROVED** [review]

**Review by quentinlesceller — APPROVED** [review]
LGTM 👍

**Pull request merged**
